services:
  mongo:
    image: docker.io/library/mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: sweetmedical
    ports:
      - 27017:27017
    volumes:
      - ./:/docker-entrypoint-initdb.d

  mongoman:
    image: ghcr.io/aientech/mongoman:main
    environment:
      - MONGODB_URI=mongodb://root:root@mongo:27017
    restart: always
    ports:
      - 8081:3000
