@startuml

Medico --> Usuario
Medico --> "*" BloqueHorario
Medico --> "1..*" Servicio
Medico --> "1..*" Sede
Medico --> "*" Notificacion

Servicio --> "1" TipoServicio

BloqueHorario --> "1" Servicio
BloqueHorario --> "1" Sede

Sede --> "1" Ubicacion

Paciente --> Usuario
Paciente --> "1" ObraSocial
Paciente --> "1" Plan
Paciente --> "*" Notificacion

ObraSocial --> "*" Plan

Plan --> "*" Cobertura

Cobertura ..> EstadoCobertura

Turno --> "1" Paciente
Turno --> "1" Medico
Turno --> "1" Servicio
Turno --> "1" Sede
Turno --> "*" EstadoTurno

EstadoTurno --> "1" Estado

class Usuario {
    id
    nombre
    notificaciones

    + recibirNotificacion(notificacion): void
    + verNotificacion(idNotificacion): void
}

class Medico {
    usuario
    nombre
    apellido
    documento
    servicios
    sedes
    agenda: [BloqueHorario]

    + generarTurnos(bloqueHorario): [Turno]
    + agregarDisponibilidad(fechaHoraInicio, fechaHoraFin, sede, servicio): BloqueHorario
}

class Servicio {
    tipoServicio
    nombre
    descripcion
    precio
    duracion
}

enum TipoServicio {
    ESPECIALIDAD
    PRACTICA
}

class BloqueHorario {
    sede
    servicios
    horaInicio
    horaFin
}

class Sede {
    nombre
    ubicacion
}

class Ubicacion {
    latitud
    longitud
}

class Paciente {
    usuario
    nombre
    apellido
    documento
    obraSocial
    plan
}

class ObraSocial {
    nombre
    planes: [Plan]
}

class Plan {
    tipo
    coberturaPorServicio: [Cobertura]

    + coberturaDe(servicio)
}

class Cobertura {
    servicio
    porcentaje

    + calcularMonto()
    + tipoCobertura(): EstadoCobertura
}

enum EstadoCobertura {
    TOTAL
    PARCIAL
    NINGUNA
}

class Turno {
    paciente
    medico
    servicio
    sede
    fechaHora
    estadosTurno: [EstadoTurno]

    + reservar(paciente, servicio): void
    + cancelar(responsable, motivo): void
    + confirmar(responsable): void
    + puedeCancelarse(): bool
    + estadoActual() : EstadoTurno
    + marcarRealizado(): void
    + puedeModificarse(): bool
    + agregarEstado(): void
}

class EstadoTurno {
    estado
    responsableCambio
    fechaHora
    motivo
}

enum Estado {
    DISPONIBLE
    RESERVADO
    CONFIRMADO
    CANCELADO
    REALIZADO
}

class Notificacion {
    id
    destinatario
    mensaje
    fechaHoraEnviado
    visto
    fechaHoraVisto

    + marcarComoVista()
}

@enduml